# ==========================================
# APPLICATION
# ==========================================
spring.application.name=backendGAP

# ==========================================
# DATABASE - PostgreSQL RENDER
# ==========================================
spring.datasource.url=jdbc:postgresql://dpg-d6jcg9hr0fns73blkgg0-a.frankfurt-postgres.render.com/gab_database
spring.datasource.username=gab_database_user
spring.datasource.password=GG0jPGCR3iSCu7dnYDfb8EJfD4bgbPpI
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# SESSION
# ==========================================
server.servlet.session.timeout=30m
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true

# ==========================================
# SERVER
# ==========================================
server.port=${PORT:8084}

# ==========================================
# ADMIN CREDENTIALS
# ==========================================
gab.admin.username=admin
gab.admin.password=admin123