# ==========================================
# APPLICATION
# ==========================================
spring.application.name=backendGAP

# ==========================================
# DATABASE - PostgreSQL
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/backendgap_db
spring.datasource.username=gap_user
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# SESSION
# ==========================================
server.servlet.session.timeout=30m
server.servlet.session.cookie.http-only=true

# ==========================================
# SERVER
# ==========================================
server.port=8084

# ==========================================
# ADMIN CREDENTIALS
# ==========================================
gab.admin.username=admin
gab.admin.password=admin123

# ==========================================
# LOGS
# ==========================================
logging.level.com.gap.backendgap=DEBUG
logging.level.org.springframework.security=DEBUG